import { z } from 'zod';
import { publicProcedure } from '../trpc';
import { Hermit } from '@drizzle/db';

export interface HermitcraftVideo {
  id: string;
  uploaded: string;
  uploadedFriendly: string;
  uploadedFriendlyMobile: string;
  uploader: Hermit;
  title: string;
  duration: number;
  friendlyDuration: string;
  likeCount: number;
  viewCount: number;
  commentCount: number;
}

type GetHermitChannelsApiResponse = Hermit[];
type GetVideosApiResponse = HermitcraftVideo[];

// must run this serverside to avoid a CORS error
export const getHermitChannels = publicProcedure
  .output(z.custom<GetHermitChannelsApiResponse>())
  .query(async () => {
    const response = await fetch('https://hermitcraft.com/api/hermit');
    if (!response.ok) {
      throw new Error('Failed to fetch channel data');
    }

    const result = await response.json();

    return result as GetHermitChannelsApiResponse;
  });

export const getHermitcraftVideos = publicProcedure
  .input(
    z.object({
      type: z.string(),
      start: z.string(),
      member: z.string().optional(),
    }),
  )
  .output(z.custom<GetVideosApiResponse>())
  .query(async ({ input: { type, start, member } }) => {
    // const response = await fetch(
    //   `https://hermitcraft.com/api/videos?type=${type}${member ? `&member=${member}` : ''}&start=${start}`,
    // );
    // if (!response.ok) {
    //   throw new Error('Failed to fetch video data');
    // }

    // const result = await response.json();
    const result = JSON.parse(JSON.stringify(ohMyGodBackupResponse));
    return result as GetVideosApiResponse;
  });

const ohMyGodBackupResponse = [
  {
    id: 'd-Mxl8-60ZA',
    uploaded: '2024-05-25T18:10:09Z',
    uploadedFriendly: '3 hours ago',
    uploadedFriendlyMobile: '3h',
    uploader: {
      id: 0,
      ChannelName: 'pearlescentmoon',
      DisplayName: 'PearlescentMoon',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AAUvwngdvXTad1pTu0aUK4tEhSKa7kQR96SVQcXaWWsGDw=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'PearlescentMoon',
      TwitchName: 'PearlescentMoon',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCIc_32utqqEhuQl9OV0zjaA',
      UploadPlaylistID: 'UU1GJ5aeqpEWklMBQ3oXrPQQ',
    },
    title: 'Hermitcraft 10: Terraforming Tango... And Pickles | Episode 16',
    duration: 1866,
    friendlyDuration: '31:06',
    likeCount: '4844',
    viewCount: 32038,
    commentCount: 224,
  },
  {
    id: 'W2qtZtZzCeg',
    uploaded: '2024-05-25T17:10:08Z',
    uploadedFriendly: '4 hours ago',
    uploadedFriendlyMobile: '4h',
    uploader: {
      id: 0,
      ChannelName: 'rendog',
      DisplayName: 'rendog',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7_Lkg0zuSa_nslliXBX9OsYpJWNr5ZPX6qOow=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'renthedog',
      TwitchName: 'rendogtv',
      WebsiteURL: '',
      Active: true,
      Streaming: true,
      YTStreaming: false,
      ChannelID: 'UCDpdtiUfcdUCzokpRWORRqA',
      UploadPlaylistID: 'UUDpdtiUfcdUCzokpRWORRqA',
    },
    title: "LET'S FINISH THE GIGATRUCK™! | HermitCraft 10 | Ep 25",
    duration: 2047,
    friendlyDuration: '34:07',
    likeCount: '1329',
    viewCount: 10626,
    commentCount: 180,
  },
  {
    id: 'QMTXm_3WJn0',
    uploaded: '2024-05-25T17:10:03Z',
    uploadedFriendly: '4 hours ago',
    uploadedFriendlyMobile: '4h',
    uploader: {
      id: 0,
      ChannelName: 'falsesymmetry',
      DisplayName: 'False',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-9_GWX940aWKZb80fbN55eGr3k-HmjsZ2ycg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'falsesymmetry',
      TwitchName: 'FalseSymmetry',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCuQYHhF6on6EXXO-_i_ClHQ',
      UploadPlaylistID: 'UUuQYHhF6on6EXXO-_i_ClHQ',
    },
    title: "Hermitcraft 10: Episode 20 | I'M MOVING IN!",
    duration: 1847,
    friendlyDuration: '30:47',
    likeCount: '816',
    viewCount: 5719,
    commentCount: 46,
  },
  {
    id: '9gZWaMlrvm8',
    uploaded: '2024-05-25T17:10:03Z',
    uploadedFriendly: '4 hours ago',
    uploadedFriendlyMobile: '4h',
    uploader: {
      id: 0,
      ChannelName: 'geminitaymc',
      DisplayName: 'GeminiTay',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AAUvwnimJZbSLxnQS4_EG9GEpDgimYg692epUEoRC0OQ3w=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'GeminiTayMC',
      TwitchName: 'geminitay',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCUBsjvdHcwZd3ztdY1Zadcw',
      UploadPlaylistID: 'UUUBsjvdHcwZd3ztdY1Zadcw',
    },
    title:
      "15 Minecraft worlds for Minecraft's 15th Anniversary #ad #minecraft15",
    duration: 48,
    friendlyDuration: '0:48',
    likeCount: '1495',
    viewCount: 7093,
    commentCount: 42,
  },
  {
    id: 'X0i0x2Zxm8E',
    uploaded: '2024-05-25T15:10:09Z',
    uploadedFriendly: '6 hours ago',
    uploadedFriendlyMobile: '6h',
    uploader: {
      id: 0,
      ChannelName: 'smallishbeans',
      DisplayName: 'Smallishbeans',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AIf8zZS5xe7ZtgbOBEnvqqaKb9kb_j3PIyEiPrvJ8MiJ=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'Smallishbeans',
      TwitchName: 'smallishbeans',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UC4qdHN4zHhd4VvNy3zNgXPA',
      UploadPlaylistID: 'UULF4qdHN4zHhd4VvNy3zNgXPA',
    },
    title: 'We Did a BAD Thing.. | Minecraft SOS | Finale',
    duration: 1717,
    friendlyDuration: '28:37',
    likeCount: '6887',
    viewCount: 59085,
    commentCount: 438,
  },
  {
    id: 'k4WJ-WV5ogs',
    uploaded: '2024-05-25T15:10:02Z',
    uploadedFriendly: '6 hours ago',
    uploadedFriendlyMobile: '6h',
    uploader: {
      id: 0,
      ChannelName: 'cubfan135',
      DisplayName: 'cubfan135',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-BJGa9Okc3w5jwu5OeW1spe_FY2VC7TMDm0Q=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'cubfan135',
      TwitchName: 'cubfan135',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UC9lJXqw4QZw-HWaZH6sN-xw',
      UploadPlaylistID: 'UU9lJXqw4QZw-HWaZH6sN-xw',
    },
    title: 'Hermitcraft 10: Cuboom Fireworks Opens! (Ep. 21)',
    duration: 1987,
    friendlyDuration: '33:07',
    likeCount: '2126',
    viewCount: 17944,
    commentCount: 156,
  },
  {
    id: '0ssV-Pf8qtw',
    uploaded: '2024-05-24T16:10:05Z',
    uploadedFriendly: '1 day ago',
    uploadedFriendlyMobile: '1d',
    uploader: {
      id: 0,
      ChannelName: 'geminitaymc',
      DisplayName: 'GeminiTay',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AAUvwnimJZbSLxnQS4_EG9GEpDgimYg692epUEoRC0OQ3w=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'GeminiTayMC',
      TwitchName: 'geminitay',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCUBsjvdHcwZd3ztdY1Zadcw',
      UploadPlaylistID: 'UUUBsjvdHcwZd3ztdY1Zadcw',
    },
    title: "I Built a Mega World for Minecraft's 15th Birthday!",
    duration: 1530,
    friendlyDuration: '25:30',
    likeCount: '14835',
    viewCount: 146112,
    commentCount: 709,
  },
  {
    id: 'KhNQHpheDzE',
    uploaded: '2024-05-24T14:10:03Z',
    uploadedFriendly: '1 day ago',
    uploadedFriendlyMobile: '1d',
    uploader: {
      id: 0,
      ChannelName: 'docm77',
      DisplayName: 'Docm77',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-gjLPd9nARXXk7R9IKOS9AtYt68nbixboTIg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'docm77',
      TwitchName: 'docm77live',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UC4O9HKe9Jt5yAhKuNv3LXpQ',
      UploadPlaylistID: 'UU4O9HKe9Jt5yAhKuNv3LXpQ',
    },
    title: 'Crafting Every Item in the Game - Hermitcraft Season 10 Episode 14',
    duration: 2618,
    friendlyDuration: '43:38',
    likeCount: '8189',
    viewCount: 112729,
    commentCount: 715,
  },
  {
    id: '8hBsaG2hRUQ',
    uploaded: '2024-05-23T14:10:06Z',
    uploadedFriendly: '2 days ago',
    uploadedFriendlyMobile: '2d',
    uploader: {
      id: 0,
      ChannelName: 'joehillstsd',
      DisplayName: 'joehills',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l788Cy63rOXC8AAibKFOQBJJqUzSO9CtJyDi8A=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'joehills',
      TwitchName: 'joehills',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCtWObtiLCNI_BTBHwEOZNqg',
      UploadPlaylistID: 'UUtWObtiLCNI_BTBHwEOZNqg',
    },
    title: 'HermitCraft 10 live!',
    duration: 7408,
    friendlyDuration: '2:03:28',
    likeCount: '82',
    viewCount: 1679,
    commentCount: 0,
  },
  {
    id: 'ChC2YPjArg8',
    uploaded: '2024-05-22T19:10:03Z',
    uploadedFriendly: '3 days ago',
    uploadedFriendlyMobile: '3d',
    uploader: {
      id: 0,
      ChannelName: 'ethoslab',
      DisplayName: 'Etho',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a-/AAuE7mA-ZIagIpZkOlXv2OhgQQDxsi3MkBBVm3KaoA=s288-mo-c-c0xffffffff-rj-k-no',
      TwitterName: 'EthoLP',
      TwitchName: 'ethotv',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCFKDEp9si4RmHFWJW1vYsMA',
      UploadPlaylistID: 'UUFKDEp9si4RmHFWJW1vYsMA',
    },
    title: 'Etho Plays Minecraft - Episode 586: Chaos To Order',
    duration: 2464,
    friendlyDuration: '41:04',
    likeCount: '25930',
    viewCount: 313012,
    commentCount: 1549,
  },
  {
    id: 'Jpqy3Cc3opA',
    uploaded: '2024-05-22T18:10:15Z',
    uploadedFriendly: '3 days ago',
    uploadedFriendlyMobile: '3d',
    uploader: {
      id: 0,
      ChannelName: 'xisumavoid',
      DisplayName: 'Xisuma',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l78q19X29K_HCXvPrJ_X4uyqEElUKvR97itnZg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'xisumavoid',
      TwitchName: 'xisuma',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCU9pX8hKcrx06XfOB-VQLdw',
      UploadPlaylistID: 'UUU9pX8hKcrx06XfOB-VQLdw',
    },
    title:
      'Minecraft 1.21 Snapshot 24W21A | Data Driven Jukeboxes & New Gamerule',
    duration: 565,
    friendlyDuration: '9:25',
    likeCount: '7315',
    viewCount: 110951,
    commentCount: 424,
  },
  {
    id: 'QBDKkuac7Tc',
    uploaded: '2024-05-21T18:10:09Z',
    uploadedFriendly: '4 days ago',
    uploadedFriendlyMobile: '4d',
    uploader: {
      id: 0,
      ChannelName: 'rendog',
      DisplayName: 'rendog',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7_Lkg0zuSa_nslliXBX9OsYpJWNr5ZPX6qOow=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'renthedog',
      TwitchName: 'rendogtv',
      WebsiteURL: '',
      Active: true,
      Streaming: true,
      YTStreaming: false,
      ChannelID: 'UCDpdtiUfcdUCzokpRWORRqA',
      UploadPlaylistID: 'UUDpdtiUfcdUCzokpRWORRqA',
    },
    title: 'WHAT THE TRUCK! | HermitCraft 10 | Ep 24',
    duration: 1452,
    friendlyDuration: '24:12',
    likeCount: '6171',
    viewCount: 80028,
    commentCount: 426,
  },
  {
    id: 'G96GVtPUpxU',
    uploaded: '2024-05-21T15:10:06Z',
    uploadedFriendly: '4 days ago',
    uploadedFriendlyMobile: '4d',
    uploader: {
      id: 0,
      ChannelName: 'thatmumbojumbo',
      DisplayName: 'MumboJumbo',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7_nKzN_UILeQrGZpqtxpGGCG0E0QPD7Bz8xQw=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'ThatMumboJumbo',
      TwitchName: 'thatmumbojumbo',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UChFur_NwVSbUozOcF_F2kMg',
      UploadPlaylistID: 'UUhFur_NwVSbUozOcF_F2kMg',
    },
    title: 'Where do I hide my Minecraft Diamonds?',
    duration: 33,
    friendlyDuration: '0:33',
    likeCount: '79128',
    viewCount: 928805,
    commentCount: 900,
  },
  {
    id: 'J60RzfN5Eio',
    uploaded: '2024-05-20T15:10:14Z',
    uploadedFriendly: '5 days ago',
    uploadedFriendlyMobile: '5d',
    uploader: {
      id: 0,
      ChannelName: 'xisumavoid',
      DisplayName: 'Xisuma',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l78q19X29K_HCXvPrJ_X4uyqEElUKvR97itnZg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'xisumavoid',
      TwitchName: 'xisuma',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCU9pX8hKcrx06XfOB-VQLdw',
      UploadPlaylistID: 'UUU9pX8hKcrx06XfOB-VQLdw',
    },
    title: 'Hermitcraft X 1164 Pig & Pickles',
    duration: 1277,
    friendlyDuration: '21:17',
    likeCount: '7685',
    viewCount: 99451,
    commentCount: 279,
  },
  {
    id: 'njI-V1a-DGw',
    uploaded: '2024-05-20T14:10:03Z',
    uploadedFriendly: '5 days ago',
    uploadedFriendlyMobile: '5d',
    uploader: {
      id: 0,
      ChannelName: 'impulsesv',
      DisplayName: 'impulseSV',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-4CGaLx7vB6_zpGA_g2muX-7dpi6nu8klPYg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'impulseSV',
      TwitchName: 'impulsesv',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCuMJPFqazQI4SofSFEd-5zA',
      UploadPlaylistID: 'UUuMJPFqazQI4SofSFEd-5zA',
    },
    title: 'This Will Be Mine! - Hermitcraft 10 | Ep 17',
    duration: 1446,
    friendlyDuration: '24:06',
    likeCount: '15111',
    viewCount: 225160,
    commentCount: 612,
  },
  {
    id: 'OWWtrcHWnao',
    uploaded: '2024-05-19T16:10:01Z',
    uploadedFriendly: '6 days ago',
    uploadedFriendlyMobile: '6d',
    uploader: {
      id: 0,
      ChannelName: 'bdoubleo100',
      DisplayName: 'BdoubleO',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-jdIst1b1IE24PWbjjN8WijYLwb62YDv9k3A=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'BdoubleO100',
      TwitchName: 'bdoubleo',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UClu2e7S8atp6tG2galK9hgg',
      UploadPlaylistID: 'UUlu2e7S8atp6tG2galK9hgg',
    },
    title: 'Minecraft Hermitcraft :: Bdubs Home-Made Super Smelter',
    duration: 2484,
    friendlyDuration: '41:24',
    likeCount: '29076',
    viewCount: 452478,
    commentCount: 1332,
  },
  {
    id: 'MInzl3HDKxY',
    uploaded: '2024-05-19T13:10:09Z',
    uploadedFriendly: '6 days ago',
    uploadedFriendlyMobile: '6d',
    uploader: {
      id: 0,
      ChannelName: 'xbxaxcx',
      DisplayName: 'xBCrafted',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-yCXpYvoqNghtNNXdgCVKecKgA9SUnxPAgOw=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'xBCrafted',
      TwitchName: 'xbcrafted',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UC_MkjhQr_D_lGlO3uu-GxyA',
      UploadPlaylistID: 'UU_MkjhQr_D_lGlO3uu-GxyA',
    },
    title: 'HermitCraft 10 | 021 | PROGRESSION!',
    duration: 1314,
    friendlyDuration: '21:54',
    likeCount: '2749',
    viewCount: 26653,
    commentCount: 73,
  },
  {
    id: 'xT2NDVjFFLE',
    uploaded: '2024-05-19T13:10:09Z',
    uploadedFriendly: '6 days ago',
    uploadedFriendlyMobile: '6d',
    uploader: {
      id: 0,
      ChannelName: 'zedaphplays',
      DisplayName: 'ZedaphPlays',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7-E32aR58QJ8arDv7464ZomvJfIH4OLd4Wumw=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'ZedaphPlays',
      TwitchName: 'ZedaphPlays',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCPK5G4jeoVEbUp5crKJl6CQ',
      UploadPlaylistID: 'UUPK5G4jeoVEbUp5crKJl6CQ',
    },
    title: '🔴 Flying Dolphins??? - Hermitcraft S10 #10.5 LIVE',
    duration: 7666,
    friendlyDuration: '2:07:46',
    likeCount: '1178',
    viewCount: 22421,
    commentCount: 42,
  },
  {
    id: 'cUG7tAca0Xg',
    uploaded: '2024-05-19T13:10:08Z',
    uploadedFriendly: '6 days ago',
    uploadedFriendlyMobile: '6d',
    uploader: {
      id: 0,
      ChannelName: 'vintagebeef',
      DisplayName: 'Vintage Beef',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l78UY9UkrkIuUS9LIg17n1fhKSIayjsugWMsTw=s288-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'vintagebeeflp',
      TwitchName: 'VintageBeef',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCu17Sme-KE87ca9OTzP0p7g',
      UploadPlaylistID: 'UUu17Sme-KE87ca9OTzP0p7g',
    },
    title: 'A NEW Way to Play! - EP19 - Hermitcraft Season 10',
    duration: 1359,
    friendlyDuration: '22:39',
    likeCount: '5933',
    viewCount: 67343,
    commentCount: 290,
  },
  {
    id: 'ePJZG8JFOfI',
    uploaded: '2024-05-18T17:10:09Z',
    uploadedFriendly: '7 days ago',
    uploadedFriendlyMobile: '7d',
    uploader: {
      id: 0,
      ChannelName: 'smallishbeans',
      DisplayName: 'Smallishbeans',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AIf8zZS5xe7ZtgbOBEnvqqaKb9kb_j3PIyEiPrvJ8MiJ=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'Smallishbeans',
      TwitchName: 'smallishbeans',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UC4qdHN4zHhd4VvNy3zNgXPA',
      UploadPlaylistID: 'UULF4qdHN4zHhd4VvNy3zNgXPA',
    },
    title: 'Massive Terraform/Village Project! | Hermitcraft 10 | Ep.17',
    duration: 1591,
    friendlyDuration: '26:31',
    likeCount: '35975',
    viewCount: 462343,
    commentCount: 1318,
  },
  {
    id: '92TsMAJz-Hg',
    uploaded: '2024-05-17T19:10:13Z',
    uploadedFriendly: '8 days ago',
    uploadedFriendlyMobile: '8d',
    uploader: {
      id: 0,
      ChannelName: 'xisumavoid',
      DisplayName: 'Xisuma',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l78q19X29K_HCXvPrJ_X4uyqEElUKvR97itnZg=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'xisumavoid',
      TwitchName: 'xisuma',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCU9pX8hKcrx06XfOB-VQLdw',
      UploadPlaylistID: 'UUU9pX8hKcrx06XfOB-VQLdw',
    },
    title: 'Minecraft Turns 15! Free Capes & How To Get Them',
    duration: 434,
    friendlyDuration: '7:14',
    likeCount: '11441',
    viewCount: 283700,
    commentCount: 673,
  },
  {
    id: 'V7rp_QX4eWw',
    uploaded: '2024-05-17T18:10:08Z',
    uploadedFriendly: '8 days ago',
    uploadedFriendlyMobile: '8d',
    uploader: {
      id: 0,
      ChannelName: 'thatmumbojumbo',
      DisplayName: 'MumboJumbo',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7_nKzN_UILeQrGZpqtxpGGCG0E0QPD7Bz8xQw=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'ThatMumboJumbo',
      TwitchName: 'thatmumbojumbo',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UChFur_NwVSbUozOcF_F2kMg',
      UploadPlaylistID: 'UUhFur_NwVSbUozOcF_F2kMg',
    },
    title: 'Mojang changed Pistons... I fixed them',
    duration: 579,
    friendlyDuration: '9:39',
    likeCount: '72712',
    viewCount: 977501,
    commentCount: 4181,
  },
  {
    id: 'i3VXbMaqvgE',
    uploaded: '2024-05-17T15:10:14Z',
    uploadedFriendly: '8 days ago',
    uploadedFriendlyMobile: '8d',
    uploader: {
      id: 0,
      ChannelName: 'zombiecleo',
      DisplayName: 'ZombieCleo',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l7_SPPaYuaxChEgGG_SEQmiym3WTEukF6A_Z1A=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'ZombieCleo',
      TwitchName: 'zombiecleo',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCjI5qxhtyv3srhWr60HemRw',
      UploadPlaylistID: 'UUjI5qxhtyv3srhWr60HemRw',
    },
    title: "WHAT'S IN THE DARK? - 12 - HERMITCRAFT SEASON 10",
    duration: 816,
    friendlyDuration: '13:36',
    likeCount: '6895',
    viewCount: 53677,
    commentCount: 289,
  },
  {
    id: 'BdUggvCbmzM',
    uploaded: '2024-05-17T15:10:08Z',
    uploadedFriendly: '8 days ago',
    uploadedFriendlyMobile: '8d',
    uploader: {
      id: 0,
      ChannelName: 'pearlescentmoon',
      DisplayName: 'PearlescentMoon',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/ytc/AAUvwngdvXTad1pTu0aUK4tEhSKa7kQR96SVQcXaWWsGDw=s288-c-k-c0x00ffffff-no-rj',
      TwitterName: 'PearlescentMoon',
      TwitchName: 'PearlescentMoon',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCIc_32utqqEhuQl9OV0zjaA',
      UploadPlaylistID: 'UU1GJ5aeqpEWklMBQ3oXrPQQ',
    },
    title: 'Hermitcraft 10: Competition Time! Win or Lose? | Episode 15',
    duration: 2326,
    friendlyDuration: '38:46',
    likeCount: '17158',
    viewCount: 208071,
    commentCount: 539,
  },
  {
    id: '5w2f0foZ5YU',
    uploaded: '2024-05-17T15:10:07Z',
    uploadedFriendly: '8 days ago',
    uploadedFriendlyMobile: '8d',
    uploader: {
      id: 0,
      ChannelName: 'joehillstsd',
      DisplayName: 'joehills',
      GooglePlusLink: '',
      ProfilePicture:
        'https://yt3.ggpht.com/a/AGF-l788Cy63rOXC8AAibKFOQBJJqUzSO9CtJyDi8A=s88-c-k-c0xffffffff-no-rj-mo',
      TwitterName: 'joehills',
      TwitchName: 'joehills',
      WebsiteURL: '',
      Active: true,
      Streaming: false,
      YTStreaming: false,
      ChannelID: 'UCtWObtiLCNI_BTBHwEOZNqg',
      UploadPlaylistID: 'UUtWObtiLCNI_BTBHwEOZNqg',
    },
    title:
      'Again! Again! My most obnoxious Balatro setup (Mime, Baron, Shoot the Moon, Brainstorm, Blueprint)',
    duration: 82,
    friendlyDuration: '1:22',
    likeCount: '185',
    viewCount: 1738,
    commentCount: 22,
  },
];
